image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-preview
  - port: 5090
    onOpen: ignore
tasks:
  - init: bundle install
    command: ruby mock_fahc.rb
    command: ruby fahcmon.rb
